# Generated by Django 5.2.7 on 2025-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Ruta relativa en static/images, p.ej. cars/car1.svg",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Precio en guaraníes (PYG)",
                max_digits=12,
            ),
        ),
    ]
