# Generated by Django 5.2.5 on 2025-10-23 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_vehicle_image_vehicle_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="end_date",
            new_name="fecha_fin",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="start_date",
            new_name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="reservation",
            name="comentarios",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("COMPLETADA", "Completada"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
