# Generated by Django 5.2.7 on 2025-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_make_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('SUV', 'SUV'), ('PICKUP', 'Camioneta'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('CAMION', 'Camión'), ('OTRO', 'Otro')], max_length=12, null=True, verbose_name='Tipo'),
        ),
    ]
