# Generated by Django 5.2.7 on 2025-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(blank=True, help_text='Ruta relativa dentro de static/images/vehicles (ej.: vehicles/ToyotaCorolla.jpg)', max_length=200, null=True),
        ),
    ]
